<?php
/**
 * Created by PhpStorm.
 * User: alisochka
 * Date: 08.08.17
 * Time: 12:46
 */
namespace app\components;
use yii\base\Widget;

class CalendarWidget extends Widget {
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function run()
    {
        return $this -> render(
            'calendar'
        );
    }

}