<?php
/**
 * Created by PhpStorm.
 * User: alisochka
 * Date: 30.08.17
 * Time: 19:08
 */
namespace app\components;
use yii\base\Widget;

class New_gWidget extends Widget {
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function run()
    {
        return $this -> render(
            'new_g'
        );
    }
}